version: "3.9"

services:
    app:
        build: .
        environment:
            DB_USER: root
            DB_PASSWORD: password
            DB_DATABASE: general
        ports:
            - "49152:3000"

    db:
        image: postgres:latest
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: general
