version: "3.9"

services:
    tornado:
        build: .
        environment:
            DB_USER: root
            DB_PASSWORD: testpassword
            DB_DATABASE: general
        ports:
            - "3000:3000"
        volumes:
            - "/workspaces/tornado/test:/root"

    db:
        image: postgres:latest
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: testpassword
            POSTGRES_USER: root
            POSTGRES_DB: general
        volumes:
            - "/tmp/db:/var/lib/postgresql/data"
